// src/app/layout.tsx
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "@/components/ui/theme-toggle-button";
import { FloatingAlertProvider } from "@/components/floating-alert";
import { AuthProvider } from "@/context/auth-context";
import AuthButtons from "@/components/auth-buttons";
// import FloatingCart from "@/components/floating-cart";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  display: "swap",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  display: "swap",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <AuthProvider>
      <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
        <head>
          <link
            rel="preload"
            href="/fonts/GeistVF.woff"
            as="font"
            type="font/woff"
            crossOrigin="anonymous"
          />
          <link
            rel="preload"
            href="/fonts/GeistMonoVF.woff"
            as="font"
            type="font/woff"
            crossOrigin="anonymous"
          />
        </head>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <FloatingAlertProvider>
              <header className="bg-white shadow-md py-4">
                <div className="container mx-auto px-4 flex justify-between items-center">
                  <h1 className="text-xl font-bold">Product Catalog</h1>
                  <div className="flex items-center space-x-4">
                    <AuthButtons />
                    <ModeToggle />
                  </div>
                </div>
              </header>
              <main>{children}</main>
              {/* <FloatingCart /> */}
            </FloatingAlertProvider>
          </ThemeProvider>
        </body>
      </html>
    </AuthProvider>
  );
}
